@startuml





/' Objects '/

abstract class Rx_Tx_interface {
	+Rx_Tx_interface()
	+~Rx_Tx_interface()
	+{abstract} get_rx_ringbuffer() : SimpleQueue<uint8_t>*
	+{abstract} is_TX_pending() : bool
	+{abstract} send_byte(uint8_t byte) : bool
	+{abstract} send_many_bytes(uint8_t* ptr_to_data, uint8_t len, uint16_t timeout) : bool
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Dependency relationships '/





/' Nested objects '/



@enduml
