#!/bin/bash
## !/usr/bin/env /lib/init/init-d-script
### BEGIN INIT INFO
# Provides:          ThetaMonitor
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: run at jobs
# Description:       Debian init script to start the daemon
#                    running at jobs.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=ThetaMonitorDaemon
DAEMON_PATH=/opt/ThetaMonitorDaemon/
DAEMON=$DAEMON_PATH/ThetaMonitorDaemon
# DAEMON_ARGS="-w $DAEMON_PATH"
DESC="ThetaMonitorDaemon"

. /lib/lsb/init-functions

case "$1" in
    start)
	log_progress_msg "starting $NAME"
	cd $DAEMON_PATH
	$DAEMON &
	#start-stop-daemon --start --quiet --exec $DAEMON 
	log_progress_msg "starting done."
	log_end_msg $ret
	;;
    stop)
	log_progress_msg "stopping $NAME"
	pid=$(/usr/bin/pidof $NAME)
	log_daemon_msg "Stopping $DESC" "$NAME" 
	start-stop-daemon --stop --exec $DAEMON --retry 30
	log_end_msg $?    
    ;;
  force-reload|reload)
    exit 3
    ;;
  restart)
    $0 stop && $0 start
    ;;
  status)
    status_of_proc $DAEMON $NAME
    exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
